### PR TITLE
Remove unused arguments

### PR DESCRIPTION
**Pull request by sago35**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hello @sago35 this PR has some merge conflicts that need to be resolved, please, due to a sync error probably on my part between the master branch and the dev branch.

Thank you!

**Comment by sago35** [comment]
UPDATED.
Please review @deadprogram 

```
$ git diff --stat 7ce702790f1913c8ab8c864579d237db2d84fd0f
 LICENSE     | 27 +++++++++++++++++++++++++++
 README.md   | 23 +----------------------
 tinyfont.go |  2 +-
 3 files changed, 29 insertions(+), 23 deletions(-)

$ git diff 7ce702790f1913c8ab8c864579d237db2d84fd0f tinyfont.go
diff --git a/tinyfont.go b/tinyfont.go
index 114a4b6..d395e22 100644
--- a/tinyfont.go
+++ b/tinyfont.go
@@ -1,4 +1,4 @@
-package tinyfont
+package tinyfont // import "tinygo.org/x/tinyfont"

 import (
        "image/color"
```

**Comment by deadprogram** [comment]
Looks good to me. @conejoninja ok to merge?

**Comment by conejoninja** [comment]
It looks good to me, merging.

**Pull request merged**
