### PR TITLE
Add unicode font and example

### PR DESCRIPTION
**Pull request by sago35**
For this PR, the tinyfontgen needed to be improved, so I improved it.
And I added a simple sample using NotoEmoji / NotoSans.

I also made a README.md, but I'll delete it if you don't need it.
* https://github.com/sago35/tinyfont/blob/add-example/examples/unicode_font/README.md
* https://github.com/sago35/tinyfont/blob/add-example/examples/unicode_font2/README.md

### CODE REVIEW

**Comment by sago35** [comment]
The bundled font was created by the following command.

```
$ tinyfontgen --package notoemoji --fontname NotoEmojiRegular12pt NotoEmoji-Regular-12pt.bdf --output NotoEmoji-Regular-12pt.go --all --verbose
Approx. 3131 bytes

$ tinyfontgen --package notoemoji --fontname NotoEmojiRegular16pt NotoEmoji-Regular-16pt.bdf --output NotoEmoji-Regular-16pt.go --all --verbose
Approx. 4551 bytes

$ tinyfontgen --package notoemoji --fontname NotoEmojiRegular20pt NotoEmoji-Regular-20pt.bdf --output NotoEmoji-Regular-20pt.go --all --verbose
Approx. 6453 bytes

$ tinyfontgen.exe --package notosans --fontname notosans12pt --output notosans12pt.go --string-file strings.txt --verbose NotoSans-Regular-12pt.bdf NotoSansThai-Regular-12pt.bdf NotoSansHebrew-Regular-12pt.bdf NotoSansCJKtc-Regular-12pt.bdf
Approx. 4059 bytes
```

**Comment by sago35** [comment]
The example is now complete.
Since we only have pyportal at the moment, all the examples will work only with pyportal.

Please review @deadprogram @conejoninja

**Comment by sago35** [comment]
wioterminal.go did not need power control, so I removed it.
Other than that, I haven't changed it.

**Comment by deadprogram** [comment]
I am going to squash/merge this now. Thank you very much @sago35 for this awesome contribution!

**Pull request merged**
