### PR TITLE
Merge pybadge and pyportal examples, and add wioterminal example

### PR DESCRIPTION
**Pull request by sago35**
I will also try to make unicode font examples and so on at least work for both pyportal and wioterminal.
The pybadge example has been merged into this PR as a preparation.
And I've added the wioterminal example.

The following commands have been verified.
I don't have pybadge so I am only checking build.

```
$ tinygo flash -size short -target wioterminal .\examples\pybadge
   code    data     bss |   flash     ram
  11104   32692    6332 |   43796   39024

$ tinygo flash -size short -target pyportal .\examples\pybadge
   code    data     bss |   flash     ram
  10728   32692    6332 |   43420   39024

$ tinygo build -o app.hex -size short -target pybadge .\examples\pybadge
   code    data     bss |   flash     ram
  11464   32692    6348 |   44156   39040
```

### CODE REVIEW

**Comment by conejoninja** [comment]
Another great contribution, thanks.

I'm ready to merge this, only issue I have, is that the three examples are inside "examples/*pybadge*" folder, not sure if a different name would be more appropiate, maybe "displays"?

**Comment by sago35** [comment]
That's certainly true.
I don't think `examples/pybadge` is a good name for it either.
I'm not good at coming up with names, so I'll rename it to `examples/displays`.

**Comment by sago35** [comment]
Rename done.

```
$ tinygo build -o app.hex -target wioterminal -size short .\examples\displays
   code    data     bss |   flash     ram
  11104   32692    6332 |   43796   39024

$ tinygo build -o app.hex -target pyportal -size short .\examples\displays
   code    data     bss |   flash     ram
  10728   32692    6332 |   43420   39024

$ tinygo build -o app.hex -target pybadge -size short .\examples\displays
   code    data     bss |   flash     ram
  11464   32692    6348 |   44156   39040
```

**Comment by conejoninja** [comment]
Thanks! Now merged

**Pull request merged**
