### PR TITLE
Add boundingbox

### PR DESCRIPTION
**Pull request by sago35**
#28 
Added a BoundingBox to check the drawing size.
It can be used in the following way.

```go
	for str, font := range strings {
		y += int16(font.YAdvance) + 10
		_, w := tinyfont.LineWidth(font, str)
		display.FillRectangle(x, y-int16(font.YAdvance), int16(w), int16(font.YAdvance), red)
		display.DrawRectangle(x, y+int16(font.BBox[3]), int16(w), int16(font.BBox[1]), green) // !!! HERE !!!
		tinyfont.WriteLine(display, font, x, y, str, white)

	}
```

### CODE REVIEW

**Comment by rsjethani** [comment]
@sago35 thank you!
the changes look good

**Comment by sago35** [comment]
. /cmd/tinyfontgen has been updated.
BBox output is now supported.

Now ready for review.

**Comment by sago35** [comment]
@deadprogram or someone else
Please review.

**Comment by sago35** [comment]
Until this PR is merged, CI will continue to fail with go.mod errors.

**Comment by deadprogram** [comment]
Thanks for the fix @sago35 now merging.

**Pull request merged**
