### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by sago35**
https://github.com/tinygo-org/tinyfont/pull/18#issuecomment-668250298

### CODE REVIEW

**Comment by sago35** [comment]
Maybe the `tinygo.org/x/drivers/ili9341` imported by examples/initdisplay/wioterminal.go is old.
I update go.mod by following.

```
go get tinygo.org/x/drivers@dev
```

**Comment by sago35** [comment]
@deadprogram 
Maybe the fix-ci branch won't give you an error.
I want to run CI.

Also, it would be great if you could address #17.

**Comment by sago35** [comment]
@deadprogram 
Maybe you need to set up the following.
I think it's probably enabled on tinygo-org/tinygo.

> By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Project Settings>Advanced of your project and set the Build forked pull requests option to On.

https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by deadprogram** [comment]
Thanks for the fixes @sago35 now merging.

**Pull request merged**
