### PR TITLE
examples: change to stay at main()

### PR DESCRIPTION
**Pull request by sago35**
Because after main(), you will not be able to tinygo flash after exiting main().
This is comfortable even without a debugger.

### CODE REVIEW

**Comment by sago35** [comment]
I would like you to merge after #18.

**Comment by deadprogram** [comment]
Hello @sago35 #18 is now merged, so you can please resolve the merge conflicts on this PR. Thank you!

**Comment by sago35** [comment]
Hello @deadprogram 
Rebased.

**Comment by deadprogram** [comment]
Makes sense, now merging. Thanks @sago35

**Pull request merged**
