### PR TITLE
feature: allow multiple ttf fonts at the same time

### PR DESCRIPTION
**Pull request by sago35**
This PR extends tinyfontgen-ttf to allow loading multiple TTF fonts, enabling simultaneous display of languages such as Japanese and Korean.

Additionally, it introduces examples/unicode_font3_const2bit using the new tinyfontgen-ttf. This ensures that issues, like the one in #43, can be detected immediately if they occur.

### CODE REVIEW

**Comment by sago35** [comment]
At this point, heap allocation remains in const2bit. This will be improved in #48.

```
$ tinygo flash -target pyportal -size short --print-allocs . ./examples/unicode_font3_const2bit
C:\Users\sago3\dev\pkg\mod\tinygo.org\x\drivers@v0.25.0\ili9341\parallel_atsamd51.go:33:26: object allocated on the heap: escapes at line 33
C:\Users\sago3\dev\pkg\mod\tinygo.org\x\drivers@v0.25.0\ili9341\parallel_atsamd51.go:28:16: object allocated on the heap: escapes at line 28
C:\Users\sago3\dev\src\tinygo.org\x\tinyfont\const2bit\const2bit.go:119:9: object allocated on the heap: escapes at line 119
C:\tinygo\tinygo\src\runtime\string.go:86:14: object allocated on the heap: size is not constant
C:\tinygo\tinygo\src\runtime\baremetal.go:43:14: object allocated on the heap: size is not constant
C:\tinygo\tinygo\src\runtime\slice.go:50:14: object allocated on the heap: size is not constant
C:\Go\src\errors\errors.go:62:21: object allocated on the heap: escapes at line 62
C:\tinygo\tinygo\src\internal\task\task_stack.go:75:24: object allocated on the heap: size is not constant
C:\tinygo\tinygo\src\internal\task\task_stack.go:113:12: object allocated on the heap: escapes at line 115
   code    data     bss |   flash     ram
  24056     228    6696 |   24284    6924
```

**Comment by sago35** [comment]
I will revise the commit message to align with the others, so I'll mark it as a draft for now. The code is already complete, so it's fine to review it if you'd like.

**Comment by sago35** [comment]
Now ready for review

**Comment by deadprogram** [comment]
This is a very cool feature @sago35 thanks for working on it! I certainly see why you needed it :smile_cat: 

Now merging.

**Pull request merged**
